sci-libs/xblas: EAPI upgraded to 7
gentoo/sci pull request #962
Opened 2020-08-01 16:38 UTC by henrikp

Removed doc IUSE due to having no real effect on the emerge.
Slight corrections to the original suggested package.

Closes: https://bugs.gentoo.org/699382
Package-Manager: Portage-3.0.1, Repoman-2.3.23
RepoMan-Options: --force
Signed-off-by: Henrik Pihl <ahvenas@gmail.com>

2020-10-20 20:34 UTC, TheChymera commented
@henrikp the build fails over here with https://ppb.chymera.eu/d4dfbf.log Some missing file...

2020-10-20 20:41 UTC, henrikp commented
I don't have access to the log file?

Kontakt Horea Christian (<notifications@github.com>) kirjutas kuupäeval T,
20. oktoober 2020 kell 23:34:

> @henrikp <https://github.com/henrikp> the build fails over here with
> https://ppb.chymera.eu/d4dfbf.log Some missing file...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/gentoo/sci/pull/962#issuecomment-713123597>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAB452CKURAJEA56JHN7YCDSLXX53ANCNFSM4PR36QPA>
> .
>

2020-10-20 20:44 UTC, TheChymera commented
@henrikp apologies, It's my self-hoste pastebin software and it keeps doing that when pasting root-owned files... Fixed now, both the link and the software ^^

2020-10-20 21:05 UTC, epsilon-0 requested changes
This is a really old ebuild that needs to be updated to proper standards, so I've left some comments for helping fix things.

Thanks a lot for helping update the repository :smile_cat:

2020-10-20 21:05 UTC, epsilon-0 commented on sci-libs/xblas/xblas-1.0.248-r2.ebuild
> +		${LINK:-$(tc-getCC)} ${LDFLAGS}  \
Replace `${LINK:-$(tc-getCC)}` by `$(tc-getLD)`, we want to use the linker configured by the user, which is present in `$(tc-getLD)`.

2020-10-20 21:05 UTC, epsilon-0 commented on sci-libs/xblas/xblas-1.0.248-r2.ebuild
> +		${LINK:-$(tc-getCC)} ${LDFLAGS}  \
Same here, replace `LINK` by the linker from toolchain.

2020-10-20 21:05 UTC, epsilon-0 commented on sci-libs/xblas/xblas-1.0.248-r2.ebuild
> +		-Wl,--whole-archive ${libstatic} -Wl,--no-whole-archive \
whole archive, followed by no whole archive...
seems kinda sus, but I'm not a linker expert.

2020-11-27 18:18 UTC, TheChymera commented
@henrikp would you be interested in incorporating the listed suggestions? We're happy to help if anything is unclear about them or you require further assistance.

2020-11-27 18:37 UTC, henrikp commented
Yes, but will get on to that (and some other things) of in half a month or
so due to lack of time currently.

Kontakt Horea Christian (<notifications@github.com>) kirjutas kuupäeval R,
27. november 2020 kell 20:18:

> @henrikp <https://github.com/henrikp> would you be interested in
> incorporating the listed suggestions? We're happy to help if anything is
> unclear about them or you require further assistance.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/gentoo/sci/pull/962#issuecomment-734944187>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAB452BMLYP433QCK6FXCTTSR7UQFANCNFSM4PR36QPA>
> .
>

2020-12-30 23:46 UTC, TheChymera commented
@henrikp bump? :3

2021-07-19 17:02 UTC, AndrewAmmerlaan commented
I think we can close this right? Since xblas has been bumped to EAPI 7 in some other commit, or are their any other import changes in this patch?

2021-07-19 17:02 UTC, closed without merging