dev-python/asdf: Add asdf package
gentoo/sci pull request #964
Opened 2020-08-20 11:40 UTC by malfatti

Hi!

This adds the package dev-python/asdf. 

I noticed repoman had some `[fatal]` in its output, but none related to these changes. I hope this is not a problem :)

Cheers
T Malfatti

2020-08-20 12:43 UTC, malfatti commented
Hi again :)

From the failed checks only those refer to dev-python/asdf:
```
dev-python/asdf/asdf-2.7.1.ebuild: BDEPEND: ~amd64-linux(default/linux/amd64/17.0/no-multilib/prefix/kernel-3.2+)
[     'dev-lang/python:3.6',
      'dev-lang/python:3.7',
      'dev-lang/python:3.8',
      'dev-lang/python:3.9']
   dev-python/asdf/asdf-2.7.1.ebuild: DEPEND: ~amd64-linux(default/linux/amd64/17.0/no-multilib/prefix/kernel-3.2+)
[     '>=dev-python/semantic_version-2.8[python_targets_python3_6(-)?,python_targets_python3_7(-)?,python_targets_python3_8(-)?,python_targets_python3_9(-)?,-python_single_target_python3_6(-),-python_single_target_python3_7(-),-python_single_target_python3_8(-),-python_single_target_python3_9(-)]',
      'dev-python/pytest[python_targets_python3_6(-)?,python_targets_python3_7(-)?,python_targets_python3_8(-)?,python_targets_python3_9(-)?,-python_single_target_python3_6(-),-python_single_target_python3_7(-),-python_single_target_python3_8(-),-python_single_target_python3_9(-)]']
   dev-python/asdf/asdf-2.7.1.ebuild: RDEPEND: ~amd64-linux(default/linux/amd64/17.0/no-multilib/prefix/kernel-3.2+)
[     '>=dev-python/semantic_version-2.8[python_targets_python3_6(-)?,python_targets_python3_7(-)?,python_targets_python3_8(-)?,python_targets_python3_9(-)?,-python_single_target_python3_6(-),-python_single_target_python3_7(-),-python_single_target_python3_8(-),-python_single_target_python3_9(-)]',
      'dev-lang/python:3.6',
      'dev-lang/python:3.7',
      'dev-lang/python:3.8',
      'dev-lang/python:3.9']
```

but I do not understand what is wrong with the dependencies. It merges fine and the package works. Could you help me to fix this?

Cheers :)

2020-08-26 00:15 UTC, malfatti commented
I think I found the problem: the PYTHON_COMPAT was set to support `python3_{6..9}`, but some dependencies only support `python3_{6..7}`. The last commit fixes this issue.

2020-09-26 21:05 UTC, epsilon-0 requested changes
Thanks a lot for the update.

2020-09-26 21:05 UTC, epsilon-0 commented on dev-python/asdf/asdf-2.7.1.ebuild
> +IUSE="doc test"
All flags and options related to testing should be done using `disutil-r1`'s functionality
Reference - https://dev.gentoo.org/~mgorny/python-guide/distutils.html
- No need to manually add a `test` USE flag
- No need to add `RESTRICT` part.
just do something like `distutils_enable_tests pytest`

2020-09-26 21:05 UTC, epsilon-0 commented on dev-python/asdf/asdf-2.7.1.ebuild
> +	dev-python/setuptools[${PYTHON_USEDEP}]
`setuptools` and other dependencies are automatically added by `inherit distutils-r1` no need to manually add them

2020-09-26 21:05 UTC, epsilon-0 commented on dev-python/asdf/asdf-2.7.1.ebuild
> +	test? ( dev-python/pytest[${PYTHON_USEDEP}] )
same with `test? ( .../pytest )`
Adding `distutils_enable_tests pytest` automatically adds this dependency.

2020-09-26 21:05 UTC, epsilon-0 commented on dev-python/asdf/asdf-2.7.1.ebuild
> +DEPEND="${RDEPEND}
Change to `BDEPEND` but also look at below comments.

2020-10-04 12:04 UTC, malfatti commented
Hey @epsilon-0,

Thanks a lot for your comments! I'm new to this, and I'm learning a lot :)
I tried to address all comments, please let me know if I misunderstood something.

Cheers :)

2020-10-04 14:27 UTC, epsilon-0 requested changes
Looks much better.

Please try to squash commits down to a single commit - https://miro.medium.com/max/700/1*fDMH5ueOLYSAef-FF2Mkqw.gif

2020-10-04 14:27 UTC, epsilon-0 commented on dev-python/asdf/asdf-2.7.1.ebuild
> +PYTHON_COMPAT=( python3_{6..7} )
can you see if you can add 3.8 and 3.9 too, change to `{6..9}`

2020-10-04 14:27 UTC, epsilon-0 commented on dev-python/asdf/metadata.xml
> +Python library for the Advanced Scientific Data Format.
formatting

2020-10-04 14:27 UTC, epsilon-0 commented on dev-python/asdf/metadata.xml
> +	</maintainer>
also add second maintainer - `sci@gentoo.org, Gentoo Science Project`

2020-10-05 20:52 UTC, malfatti commented
All done. When I opened the issue, some dependencies did not support python 3_{8..9} but now they do :)

Cheers

2020-10-05 21:05 UTC, epsilon-0 commented
Looks good at first glance, will test and report back.

2020-10-06 13:58 UTC, epsilon-0 commented
Hmm, seems like its not doing the tests correctly.
It gives the error on enabling tests
```
[32;01m * [39;49;00mPackage:    dev-python/asdf-2.7.1
[32;01m * [39;49;00mRepository: science
[32;01m * [39;49;00mMaintainer: malfatti@disroot.org sci@gentoo.org
[32;01m * [39;49;00mUSE:        abi_x86_64 amd64 elibc_glibc kernel_linux python_targets_python3_7 test userland_GNU
[32;01m * [39;49;00mFEATURES:   network-sandbox preserve-libs sandbox test userpriv usersandbox
[32;01m * [39;49;00mPackage:    dev-python/asdf-2.7.1
[32;01m * [39;49;00mRepository: science
[32;01m * [39;49;00mMaintainer: malfatti@disroot.org sci@gentoo.org
[32;01m * [39;49;00mUSE:        abi_x86_64 amd64 elibc_glibc kernel_linux python_targets_python3_7 test userland_GNU
[32;01m * [39;49;00mFEATURES:   network-sandbox preserve-libs sandbox test userpriv usersandbox
>>> Unpacking source...
>>> Unpacking asdf-2.7.1.tar.gz to /var/tmp/portage/dev-python/asdf-2.7.1/work
>>> Source unpacked in /var/tmp/portage/dev-python/asdf-2.7.1/work
>>> Preparing source in /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1 ...
 [32;01m*[0m python3_7: running distutils-r1_run_phase distutils-r1_python_compile
python3.7 setup.py build -j 5
running build
running build_py
creating /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf
copying asdf/__init__.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf
copying asdf/_convenience.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf
copying asdf/_display.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf
copying asdf/_internal_init.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf
copying asdf/asdf.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf
copying asdf/asdftypes.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf
copying asdf/block.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf
copying asdf/compression.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf
copying asdf/conftest.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf
copying asdf/constants.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf
copying asdf/exceptions.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf
copying asdf/extension.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf
copying asdf/fits_embed.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf
copying asdf/generic_io.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf
copying asdf/reference.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf
copying asdf/resolver.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf
copying asdf/schema.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf
copying asdf/search.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf
copying asdf/stream.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf
copying asdf/tagged.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf
copying asdf/treeutil.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf
copying asdf/type_index.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf
copying asdf/types.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf
copying asdf/util.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf
copying asdf/version.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf
copying asdf/versioning.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf
copying asdf/yamlutil.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf
package init file 'asdf-standard/schemas/__init__.py' not found (or not a regular file)
package init file 'asdf-standard/reference_files/__init__.py' not found (or not a regular file)
creating /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/pytest_asdf
copying pytest_asdf/__init__.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/pytest_asdf
copying pytest_asdf/plugin.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/pytest_asdf
running egg_info
writing asdf.egg-info/PKG-INFO
writing dependency_links to asdf.egg-info/dependency_links.txt
writing entry points to asdf.egg-info/entry_points.txt
writing requirements to asdf.egg-info/requires.txt
writing top-level names to asdf.egg-info/top_level.txt
reading manifest file 'asdf.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'ez_setup.py'
warning: no files found matching 'ah_bootstrap.py'
warning: no files found matching 'setup_helpers.py'
warning: no files found matching '*.c' under directory '*.pyx'
warning: no files found matching '*.pxd' under directory '*.pyx'
warning: no files found matching '*' under directory 'cextern'
warning: no files found matching '*' under directory 'scripts'
no previously-included directories found matching 'build'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'docs/api'
warning: no files found matching '*' under directory 'astropy_helpers'
warning: no previously-included files found matching 'astropy_helpers/.git'
warning: no previously-included files found matching 'astropy_helpers/.gitignore'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.o' found anywhere in distribution
writing manifest file 'asdf.egg-info/SOURCES.txt'
creating /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf/commands
copying asdf/commands/__init__.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf/commands
copying asdf/commands/defragment.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf/commands
copying asdf/commands/diff.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf/commands
copying asdf/commands/exploded.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf/commands
copying asdf/commands/extension.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf/commands
copying asdf/commands/extract.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf/commands
copying asdf/commands/info.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf/commands
copying asdf/commands/main.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf/commands
copying asdf/commands/remove_hdu.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf/commands
copying asdf/commands/tags.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf/commands
copying asdf/commands/to_yaml.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf/commands
creating /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf/commands/tests
copying asdf/commands/tests/__init__.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf/commands/tests
copying asdf/commands/tests/test_defragment.py -> /var/tmp/portage/dev-python/asdf-2.7.1/work/asdf-2.7.1-python3_7/lib/asdf/commands/tests
copying asdf/com [...]

2020-11-13 19:02 UTC, malfatti commented
Hi!

Sorry for the delay. After investigating the test issue, it looks like the test function depends on `dev-python/astropy`, which only have a live version available. Apparently, the issue can be resolved by adding `from astropy.tests.pytest_plugins import *` in the `conftest.py` file.

Since, with tests disabled, the package merges fine and is completely functional, would it be acceptable remove test from this ebuild? I ask because I don't know if it will be a good idea to add a live package as a dependency for the test flag.

2020-11-13 22:59 UTC, epsilon-0 commented
> Hi!
> 
> Sorry for the delay. After investigating the test issue, it looks like the test function depends on `dev-python/astropy`, which only have a live version available. Apparently, the issue can be resolved by adding `from astropy.tests.pytest_plugins import *` in the `conftest.py` file.
> 
> Since, with tests disabled, the package merges fine and is completely functional, would it be acceptable remove test from this ebuild? I ask because I don't know if it will be a good idea to add a live package as a dependency for the test flag.

big ooof.
astropy update is non trivial. There's quite a few packages that we need to update, though none are hard in and of themselves.

**ideally** we would like to get astropy updated as well. But seems like we have no takers.
I've asked in #science on freenode, lets wait to see if someone takes it.

2021-01-05 08:08 UTC, TheChymera commented
@malfatti Tried this again since @AndrewAmmerlaan recently fixed up astropy. The test suite still fails, however, with the same error. I have to say, it really looks like it's related to an optional `rst` documentation feature probably provided by an ancillary pytest-* package: [build.log](https://github.com/gentoo/sci/files/5768813/build.log).

In such cases it may be better to override the pytest command so as to avoid this option. Alternatively you can find out which ancillary package it is (maybe `dev-python/pytest-doctestplus`?), and add that as well.

Also, please always remember to run repoman:

```
chymera@silenthost ~/src/overlay/dev-python/asdf $ repoman full

RepoMan scours the neighborhood...
  metadata.warning              1
   dev-python/asdf/metadata.xml: inconsistent use of tabs and spaces in indentation
```

Always use tabs, never spaces :)

Sorry this is taking so long, but we're almost there!

2021-01-05 09:30 UTC, AndrewAmmerlaan commented
>  The test suite still fails, however, with the same error. I have to say, it really looks like it's related to an optional rst documentation feature probably provided by an ancillary pytest-* package: build.log.

These are the test deps accroding to upstream setup.cfg:
```
tests = 
	pytest<6
	astropy
	gwcs
	pytest-doctestplus
	pytest-remotedata
	pytest-openfiles
	psutil
```

Pytest-doctestplus was just added to the repo. pytest-remotedata sounds like something that will try to fetch things from the internet, so I'm not sure if the test suite will work at all in an ebuild, perhaps `RESTRICT="test" is required here.

2021-01-05 09:51 UTC, TheChymera commented
>  perhaps `RESTRICT="test" is required here

I wouldn't go overboard with that, pytest is quite malleable, and generally it's possible to edit the execution options in order to make it compatible with the environment portage provides. Lots of Python packages do just that, and half a test suite is better than no test suite. Absolutely worst case scenario you can patch broken test and mark them for skip after reporting to upstream, e.g.

```
sci-visualization/fsleyes/files/fsleyes-0.32.0-tests_fail.patch
11:+@pytest.mark.skip(reason="Known to fail on Gentoo:"
12-+    "https://github.com/pauldmccarthy/fsleyes/issues/38"
13-+    )
--
22:+@pytest.mark.skip(reason="Known to fail on Gentoo:"
23-+    "https://github.com/pauldmccarthy/fsleyes/issues/38"
24-+    )
--
32:+@pytest.mark.skip(reason="Known to fail on Gentoo:"
33-+    "https://github.com/pauldmccarthy/fsleyes/issues/38"
34-+    )
--
42:+@pytest.mark.skip(reason="Known to fail on Gentoo:"
43-+    "https://github.com/pauldmccarthy/fsleyes/issues/38"
44-+    )
--
56:+@pytest.mark.skip(reason="Known to fail on Gentoo:"
57-+    "https://github.com/pauldmccarthy/fsleyes/issues/38"
58-+    )
```

2021-01-05 11:52 UTC, AndrewAmmerlaan commented on dev-python/asdf/asdf-2.7.1.ebuild
> +IUSE="doc"
`IUSE="doc"` is already added by the `distutils_enable_sphinx` function

2021-01-14 21:19 UTC, closed without merging