adding freefem-4.6
gentoo/sci pull request #967
Opened 2020-08-26 16:58 UTC by Fougeroc

2020-09-26 00:15 UTC, thesamesam requested changes

2020-09-26 00:15 UTC, thesamesam commented on sci-mathematics/freefem++/freefem++-4.6.ebuild
> +EAPI=5
EAPI 7 if you can?

2020-09-26 00:15 UTC, thesamesam commented on sci-mathematics/freefem++/freefem++-4.6.ebuild
> +RDEPEND="
Sort these? (conditionals last)

2020-09-26 00:15 UTC, thesamesam commented on sci-mathematics/freefem++/freefem++-4.6.ebuild
> +	virtual/pkgconfig
all of these are likely BDEPEND on EAPI 7

2020-09-26 00:15 UTC, thesamesam commented on sci-mathematics/freefem++/freefem++-4.6.ebuild
> +# Copyright 1999-2015 Gentoo Foundation
Wrong header. Use repoman commit?

2020-09-26 00:24 UTC, epsilon-0 requested changes

2020-09-26 00:24 UTC, epsilon-0 commented on sci-mathematics/freefem++/freefem++-4.6.ebuild
> +inherit git-r3 autotools eutils flag-o-matic mpi versionator toolchain-funcs
It is a versioned ebuild, do not use `git-r3`

2020-09-26 00:24 UTC, epsilon-0 commented on sci-mathematics/freefem++/freefem++-4.6.ebuild
> +EGIT_REPO_URI="https://github.com/FreeFem/FreeFem-sources"
Again, same as above, its versioned so use a `SRC_URI`

2020-09-26 00:24 UTC, epsilon-0 commented on sci-mathematics/freefem++/freefem++-4.6.ebuild
> +src_prepare() {
No need for this, it is done automatically.

2021-07-18 09:38 UTC, closed without merging

2021-07-18 09:39 UTC, AndrewAmmerlaan commented
Closing as the latest version of freefem++ in ::sci is 4.7.1 already.