sci-astronomy/libthesky: Fix build failure with USE=static-libs.
gentoo/sci pull request #977
Opened 2020-10-03 19:34 UTC by MarcvdSluys

sci-astronomy/libthesky-0.4.1 fails to build with USE=static-libs.  Using emake as the CMake Makefile
generator, instead of ninja, fixes this.

Package-Manager: Portage-3.0.4, Repoman-3.0.1

2020-10-03 20:14 UTC, epsilon-0 requested changes
Thanks a lot for the PR.
They look good with very minor changes requested.

2020-10-03 20:14 UTC, epsilon-0 commented on sci-astronomy/libthesky/libthesky-0.4.1.ebuild
> +
Could you move this to just below the `inherit cmake...` at the top of the file?

2020-10-03 20:14 UTC, epsilon-0 commented on sci-astronomy/libthesky/libthesky-0.4.1.ebuild
>  DEPEND="~sci-libs/libsufr-0.7.5[static-libs?]"
Could you also revision bump both `libthesky-0.4.1-r1` and `libsufr-0.7.5-r1`?

2020-10-03 20:16 UTC, epsilon-0 commented
Also asking, because we are short on personnel, if you would like to take maintainership of the packages as the previous maintainer has not bothered to keep it up to date.

We would really appreciate it.

2020-10-04 09:26 UTC, MarcvdSluys commented
I would like to try that.  I've never become overconfident with writing ebuilds though.  (I always feel that once I got the hang after much trial and error, the EAPI changes and I can start from scratch).  But I could try a low number of packages...

2020-10-04 14:15 UTC, epsilon-0 commented
@MarcvdSluys 
Thanks a lot for the offer, even just managing these two packages is a lot of help thanks :)

Could you add your name to the metadata file, remove the previous committer and put your name/email in their place.
Similar to the other comments by @TheChymera, try to squash all commits into one commit
Heres a small tutorial for that, shoudn't take more than a couple of seconds - 
https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec  
https://miro.medium.com/max/700/1*fDMH5ueOLYSAef-FF2Mkqw.gif

2020-10-05 18:19 UTC, MarcvdSluys commented
@epsilon-0 OK, I force pushed to overwrite my earlier commits here.  Is that standard practice (since it's my branch anyway)?  So I 1) fixed the ebuild, 2) revision bumped and 3) updated the metadata to adopt the package (and all in a single commit ;-)).

2020-10-05 20:29 UTC, epsilon-0 commented
@MarcvdSluys 
Awesome, thanks a lot.
I will merge this shortly.

2020-10-06 21:55 UTC, epsilon-0 commented
I've merged it in 1c8c2fd90ddc3b4c5f541f46aa0dacd466ed60f3

2020-12-08 14:52 UTC, closed without merging