sci-libs/HDF5Plugin-Zstandard: add this ebuild
gentoo/sci pull request #987
Opened 2020-11-21 10:33 UTC by littlewu2508

Zstdandard compress filter plugin for hdf5
Initial commit, add ebuilds and metedata. Support Gentoo-Prefix

Package-Manager: Portage-3.0.5, Repoman-3.0.1
Signed-off-by: Yiyang Wu <xgreenlandforwyy@gmail.com>

2020-11-21 10:41 UTC, epsilon-0 requested changes

2020-11-21 10:41 UTC, epsilon-0 commented on sci-libs/HDF5Plugin-Zstandard/HDF5Plugin-Zstandard-1.0_pre20190212.ebuild
> +CMAKE_MAKEFILE_GENERATOR=ninja
This is the default. No need to add this line.

2020-11-21 10:41 UTC, epsilon-0 commented on sci-libs/HDF5Plugin-Zstandard/HDF5Plugin-Zstandard-1.0_pre20190212.ebuild
> +SRC_URI="https://github.com/aparamon/HDF5Plugin-Zstandard/archive/d5afdb5f04116d5c2d1a869dc9c7c0c72832b143.tar.gz -> HDF5Plugin-Zstandard.tar.gz"
Change this to 
`https://github.com/aparamon/HDF5Plugin-Zstandard/archive/${COMMIT}.tar.gz -> ${P}.tar.gz`
And then add a line before it saying
`COMMIT=d5afdb5f04116d5c2d1a869dc9c7c0c72832b143`

2020-11-21 10:41 UTC, epsilon-0 commented on sci-libs/HDF5Plugin-Zstandard/HDF5Plugin-Zstandard-1.0_pre20190212.ebuild
> +
Add a line setting setting `S`
`S=${PN}-${COMMIT}`
This allows you to get rid of the `mv` in `src_prepare`.

2020-11-21 10:41 UTC, epsilon-0 commented on sci-libs/HDF5Plugin-Zstandard/HDF5Plugin-Zstandard-1.0_pre20190212.ebuild
> +IUSE=""
Remove empty `IUSE`.

2020-11-21 10:41 UTC, epsilon-0 commented on sci-libs/HDF5Plugin-Zstandard/HDF5Plugin-Zstandard-1.0_pre20190212.ebuild
> +BDEPEND=""
Remove empty `BDEPEND`

2020-11-21 10:41 UTC, epsilon-0 commented on sci-libs/HDF5Plugin-Zstandard/HDF5Plugin-Zstandard-1.0_pre20190212.ebuild
> +src_unpack () {
After setting the `S` from the above comment, you can get rid of this function.

2020-11-21 11:52 UTC, littlewu2508 commented
Thanks for these reviews! See https://github.com/gentoo/sci/pull/987/commits/57b787e5c89ef981439a5f87a0271eec536c2646 for the modification

I also changed the package version, after consulting @heroxbd

2020-11-22 00:00 UTC, epsilon-0 commented
@littlewu2508 could you squash all of this into one commit.
Also change the commit message to describe what the package is, something like:
```
sci-libs/HDF5Plugin-Zstandard: new zstd plugin for hdf5

Signed-off-by: ...
```
No need for saying `adding this ebuild`.

2020-11-22 03:21 UTC, littlewu2508 commented
> 
> 
> @littlewu2508 could you squash all of this into one commit.
> Also change the commit message to describe what the package is, something like:
> 
> ```
> sci-libs/HDF5Plugin-Zstandard: new zstd plugin for hdf5
> 
> Signed-off-by: ...
> ```
> 
> No need for saying `adding this ebuild`.

I rebased them into this commit https://github.com/gentoo/sci/commit/9b11fd4356344edae07d96d01f692341df9f4e07 with the correct commit message

2020-11-22 03:32 UTC, epsilon-0 commented
You need to regenerate the manifest.
Currently the manifest is for an incorrect version.

2020-11-22 04:33 UTC, littlewu2508 commented
> 
> 
> You need to regenerate the manifest.
> Currently the manifest is for an incorrect version.

Oops. Now the manifest is regenerated.

2020-11-22 04:38 UTC, closed without merging

2020-11-22 04:39 UTC, epsilon-0 commented
merged

2020-11-22 04:43 UTC, epsilon-0 commented
Thanks for the contribution :heart: